import { Router } from 'express';
import { requireAuth, type ACoolRequest } from '../middleware/ACoolIAM.js';
import { getGoogleAccessToken } from './ACoolGoogleAccessToken.js';

const router = Router();

const allowedEncodings = new Set(['MP3', 'OGG_OPUS', 'LINEAR16']);

export const normalizeSpeechRequest = (body: Record<string, unknown>) => {
  const text = typeof body.text === 'string' ? body.text.trim() : '';
  const ssml = typeof body.ssml === 'string' ? body.ssml.trim() : '';
  if ((!text && !ssml) || (text && ssml)) throw new Error('provide_exactly_one_of_text_or_ssml');
  const input = text || ssml;
  if (input.length > 5_000) throw new Error('speech_input_too_long');

  const languageCode = typeof body.language_code === 'string' && body.language_code.trim()
    ? body.language_code.trim().slice(0, 20)
    : 'en-US';
  const voiceName = typeof body.voice_name === 'string' && body.voice_name.trim()
    ? body.voice_name.trim().slice(0, 120)
    : undefined;
  const audioEncoding = typeof body.audio_encoding === 'string'
    ? body.audio_encoding.toUpperCase()
    : 'MP3';
  if (!allowedEncodings.has(audioEncoding)) throw new Error('unsupported_audio_encoding');

  return {
    input: text ? { text } : { ssml },
    voice: { languageCode, ...(voiceName ? { name: voiceName } : {}) },
    audioConfig: {
      audioEncoding,
      speakingRate: Number(body.speaking_rate ?? 1),
      pitch: Number(body.pitch ?? 0),
    },
  };
};

router.use(requireAuth);

router.post('/synthesize', async (request: ACoolRequest, response) => {
  try {
    const payload = normalizeSpeechRequest(request.body ?? {});
    const token = await getGoogleAccessToken();
    const cloudResponse = await fetch('https://texttospeech.googleapis.com/v1/text:synthesize', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(20_000),
    });
    const result = await cloudResponse.json() as { audioContent?: string; error?: { message?: string } };
    if (!cloudResponse.ok || !result.audioContent) {
      throw new Error(result.error?.message || `google_tts_failed_${cloudResponse.status}`);
    }
    return response.json({
      audio_base64: result.audioContent,
      mime_type: payload.audioConfig.audioEncoding === 'MP3'
        ? 'audio/mpeg'
        : payload.audioConfig.audioEncoding === 'OGG_OPUS'
          ? 'audio/ogg'
          : 'audio/wav',
      generated_at: new Date().toISOString(),
      disclosure: 'Synthetic voice generated by Google Cloud Text-to-Speech.',
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'speech_synthesis_failed';
    const status = message.startsWith('provide_') || message.startsWith('speech_') || message.startsWith('unsupported_') ? 400 : 503;
    return response.status(status).json({ error: message });
  }
});

export default router;
